- name: add proxy
  become: yes
  lineinfile: 
    line: "HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/\nHTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/\nhttp_proxy=http://wwwproxy.unimelb.edu.au:8000/\nhttps_proxy=http://wwwproxy.unimelb.edu.au:8000/\nno_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
    dest: /etc/environment

- name: apt update
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- include_tasks: docker.yaml



    